import type { Metadata } from 'next'
import './globals.css'

// 定义网页的元数据
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// --------------------------- RootLayout 组件 ----------------------------
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
