import './globals.css'
import type { FC } from 'react'
import type { Metadata } from 'next'
import type { RootLayoutProps } from './type'

// 定义静态 metadata object
export const metadata: Metadata = {
  title: {
    template: '%s | NextJs', // 子路由的标题会代替 %s
    default: 'NextJs - Default - Title',
    absolute: '',
  },
  description: 'Generated by create next app',
}

// --------------------------- RootLayout 组件 ----------------------------
// children 用于渲染 page.js 文件中的 UI 组件或嵌套布局 UI 组件
const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'lightblue',
            padding: '1rem',
          }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: 'red',
            padding: '1rem',
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}

export default RootLayout
